name: 'Action workflow with other triggers'

on: 

    schedule:
     - cron: "0/5 * * * 0-6"
    push:
     
jobs:
    run-github-actions:
        runs-on: ubuntu-latest
        steps:
         - name: list files
           run:
               pwd
               ls
               ll
               lll
               echo "new testing and stuff"
         - name: new tests
           run:
            echo "returning to lessons after some time"
    # try-another-job:
    #     runs-on: ubuntu
    #     steps:
    #         - name: new tests after some time 
    #           run:
    #             node 1+1 
    #             echo 3+3 
    #             echo Done        
         
                   


