name : Git-hub-actions 

on: [push]

jobs:
    run-git-hub-external-actions :
      runs-on: ubuntu-20.04
      steps:
        - name: Simple Greeting JS action
          uses:  actions/hello-world-javascript-action@v1
          with:
                who-to-greet : Elton Vilanculo
        - name: Greeting JS output
          run: echo "${{setps.greet.output.time}}"
               echo "Done!"
            
                     

