name : Github Actions 
on: push 
jobs:
    create-issue:
        runs-on: ubuntu-latest
        steps:
            - name: Debug my first commit 
              run: |
                   echo "Im' here" 

